version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - cd docs && python configure.py
      - cd docs && doxygen Doxyfile

mkdocs:
  configuration: mkdocs.yml