version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python docs/configure.py
      - doxygen docs/Doxyfile
      - ls -l docs
      - ls -l docs/doxygen
      - ls -l docs/doxygen/html

mkdocs:
  configuration: mkdocs.yml