version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - cd docs && python conf.py
      - cd docs && doxygen Doxyfile

sphinx:
    configuration: docs/conf.py
    python_version: 3.12
    builder: html
    fail_on_warning: false
    fail_on_error: true
    output_dir: docs/_build/html
    source_dir: docs
    build_dir: docs/_build
    clean: true
    requirements_file: docs/requirements.txt