name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - develop

variables:
  SOURCE_DIR: '$(System.DefaultWorkingDirectory)'
  BUILD_DIR: '$(SOURCE_DIR)/build'
  INSTALL_DIR: '$(SOURCE_DIR)/libsbmlnetworkeditor-$(Agent.OS)'
  LIBSBML_INSTALL_PREFIX: '$(SOURCE_DIR)/libsbml'
  SWIG_SOURCE_DIR: '$(SOURCE_DIR)/swig'
  SWIG_INSTALL_PREFIX: '$(SWIG_SOURCE_DIR)/install-azure'
  SWIG_EXECUTABLE: '$(SWIG_INSTALL_PREFIX)/bin/swig'

stages:
  - stage: Build

    jobs:
    - job: BuildCppOnMac

      timeoutInMinutes: "0"
      displayName: BuildLibSBMLNetworkEditorCppOnMac
      continueOnError: "false"

      pool:
        vmImage: 'macOS-11'
        demands:
          - cmake

      strategy:
        matrix:
          Mac_Release:
            BUILD_TYPE: Release
          Mac_Debug:
            BUILD_TYPE: Debug

      steps:
      - task: CMake@1
          displayName: 'CMake ..'
          inputs:
            workingDirectory: ${BUILD_DIR}
            cmakeArgs: '..'


