site_name: My Documentation
nav:
  - Home: docs/source/index.md
  - Getting Started:
      - Introduction: docs/source/getting-started/introduction.md
      - Installation: docs/source/getting-started/installation.md
      - Configuration: docs/source/getting-started/configuration.md
  - Usage:
      - Overview: docs/source/usage/introduction.md
      - Examples: docs/source/usage/examples.md
      - Troubleshooting: docs/source/usage/troubleshooting.md

  - API Reference:
      - Overview: docs/source/api-reference/introduction.md
      - C API: docs/source/api-reference/modules/c_module.md
      - C++ API: docs/source/api-reference/modules/cpp_module.md
      - Python API: docs/source/api-reference/modules/python_module.md
