name: CMake (rapid build on push)

#on:
  #push:
    #tags:
      #- v*
on:
  push:
    branches:
      - 'develop'

env:
  BUILD_TYPE: Release

jobs:
  build_on_OSs:
    name:
      Build on ${{ matrix.platform }} with Python${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["windows-latest", "macos-latest", "ubuntu-latest"]
        cpp_standard: [ 20 ]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout libsbml
        uses: actions/checkout@v3
        with:
          repository: sbmlteam/libsbml

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Add msbuild to PATH on Windows
        if: matrix.platform == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1.6.0

      - name: Cache dependencies on Windows
        if: matrix.platform == 'windows-latest'
        id: cache-win-dependencies-static-for-libsbml
        uses: actions/cache@v3
        with:
          path: |
            ./dependencies
          key: ${{ runner.os }}-dependencies-static

      - name: Download pre-built dependencies for libsbml on Windows
        if: matrix.platform == 'windows-latest' && steps.cache-win-dependencies-static-for-libsbml.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L https://github.com/sbmlteam/libSBML-dependencies/releases/download/latest/libSBML-dependencies-1.0.1-x64-Release-static.zip > dependencies.zip
          unzip dependencies.zip
          mv libSBML-dependencies-1.0.1-x64-Release-static dependencies

      - name: Download SWIG on Windows
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          curl -L https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip/download > swig.zip
          unzip -o swig.zip -d swig
          echo $GITHUB_WORKSPACE"/swig/swigwin-4.0.2/" >> "${GITHUB_PATH}"

      - name: Add libsbml install directory to path on Windows
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          echo "D:/a/libSBMLNetworkEditor/install-libsbml/lib/cmake" >> $GITHUB_PATH

      - name: Install dependencies on Ubuntu
        if: matrix.platform == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y check ccache
          git clone https://github.com/libexpat/libexpat
          cmake -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DEXPAT_BUILD_TESTS=OFF -DEXPAT_BUILD_TOOLS=OFF -DEXPAT_BUILD_EXAMPLES=OFF -DEXPAT_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=./dependencies -B libexpat -S libexpat/expat 
          cmake --build libexpat
          cmake --install libexpat

      - name: Add libsbml install directory to path on Ubuntu
        if: matrix.platform == 'ubuntu-latest'
        shell: bash
        run: |
          echo "${{runner.workspace}}/install-libsbml/lib/cmake" >> $GITHUB_PATH

      - name: Install dependencies on macOS
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          brew install check swig ccache

      - name: Add libsbml install directory to path on macOS
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          echo "${{runner.workspace}}/install-libsbml/lib/cmake" >> $GITHUB_PATH

      - name: Prepare ccache timestamp on non-Windows
        if: matrix.platform != 'windows-latest'
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: Set ccache cache directory on non-Windows
        if: matrix.platform != 'windows-latest'
        shell: bash
        run: |
          echo "CCACHE_DIR=${{runner.workspace}}/.ccache" >> "${GITHUB_ENV}"
          echo "COMPILER_LAUNCHER=ccache" >> "${GITHUB_ENV}"

      - name: Cache ccache files on non-Windows
        if: matrix.platform != 'windows-latest'
        uses: actions/cache@v3
        with:
          path: ${{runner.workspace}}/.ccache
          key:
            ${{ runner.os }}-${{ steps.ccache_cache_timestamp.outputs.timestamp
            }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
            ${{ runner.os }}-

      - name: Create libsbml build directory
        run: cmake -E make_directory ${{runner.workspace}}/build-libsbml

      - name: Configure CMake for libsbml
        shell: bash
        working-directory: ${{runner.workspace}}/build-libsbml
        run: |
          cmake $GITHUB_WORKSPACE \
          -G "Ninja" \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_C_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
          -DWITH_CHECK=True \
          -DWITH_LIBXML=ON \
          -DENABLE_LAYOUT="ON" \
          -DENABLE_RENDER="ON" \
          -DCMAKE_INSTALL_PREFIX="${{runner.workspace}}/install-libsbml"

      - name: Build and Install libsbml
        working-directory: ${{runner.workspace}}/build-libsbml
        shell: bash
        run: |
          cmake --build . --target install --config $BUILD_TYPE

      - name: Checkout libsbmlnetworkeditor
        uses: actions/checkout@v3
        with:
          repository: adelhpour/libSBMLNetworkEditor

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}

      - name: Cache dependencies on Windows
        if: matrix.platform == 'windows-latest'
        id: cache-win-dependencies-static-for-libsbmlnetworkeditor
        uses: actions/cache@v3
        with:
          path: |
            ./dependencies
          key: ${{ runner.os }}-dependencies-static

      - name: Download pre-built dependencies on Windows
        if: matrix.platform == 'windows-latest' && steps.cache-win-dependencies-static-for-libsbmlnetworkeditor.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L https://github.com/sbmlteam/libSBML-dependencies/releases/download/latest/libSBML-dependencies-1.0.1-x64-Release-static.zip > dependencies.zip
          unzip dependencies.zip
          mv libSBML-dependencies-1.0.1-x64-Release-static dependencies

      - name: Add Windows dependencies to PATH
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: echo "D:/a/libSBMLNetworkEditor/libSBMLNetworkEditor/dependencies/" >> "${GITHUB_PATH}"

      - name: Install Graphviz on Windows
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          curl -L https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/2.50.0/msys2_3.3.3-341.x86_64_Graphviz-2.50.0-win64.zip > graphviz.zip
          unzip graphviz.zip
          mv Graphviz-2.50.0-win64 graphviz
          echo "GRAPHVIZ_PATH=D:/a/libSBMLNetworkEditor/libSBMLNetworkEditor/graphviz" >> "${GITHUB_ENV}"

      - name: Install Graphviz on Ubuntu
        if: matrix.platform == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt install -y graphviz-dev
          echo "GRAPHVIZ_PATH=${{runner.workspace}}/graphviz" >> "${GITHUB_ENV}"

      - name: Install Graphviz on macOS
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          brew install graphviz
          echo "GRAPHVIZ_PATH=/usr/local/Cellar/graphviz/8.1.0" >> "${GITHUB_ENV}"

      - name: Create libsbmlNetworkEditor build directory
        run: cmake -E make_directory ${{runner.workspace}}/build-libsbmlNetworkEditor

      - name: Configure CMake for libsbmlNetworkEditor
        shell: bash
        working-directory: ${{runner.workspace}}/build-libsbmlNetworkEditor
        run: |
          cmake $GITHUB_WORKSPACE \
          -G "Ninja" \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_C_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
          -DGRAPHVIZ_PREFIX=${GRAPHVIZ_PATH} \
          -DWITH_PYTHON="ON" \
          -DPYTHON_INSTALL_WITH_SETUP="ON" \
          -DPython_REQUIRED_VERSION=${{matrix.python_version}} \
          -DCMAKE_INSTALL_PREFIX="${{runner.workspace}}/install-libsbmlnetworkeditor"

      - name: Build and Install libsbmlnetworkeditor
        working-directory: ${{runner.workspace}}/build-libsbmlNetworkEditor
        shell: bash
        run: cmake --build . --target install --config $BUILD_TYPE

      - name: Upload binary archives
        uses: actions/upload-artifact@v3
        with:
          name: binaries for ${{ matrix.platform }} with Python${{ matrix.python_version }}
          path: ${{runner.workspace}}/install-libsbmlnetworkeditor/*
          retention-days: 1
          if-no-files-found: error

  build_on_ManyLinux:
    name:
      Build on ${{ matrix.container }} with Python${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest"]
        cpp_standard: [ 20 ]
        python_version: [ "3.8", "3.9", "3.10", "3.11" ]
        container: ["quay.io/pypa/manylinux2014_x86_64"]
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container}}

    steps:
      - name: Checkout libsbml
        uses: actions/checkout@v3
        with:
          repository: sbmlteam/libsbml

      - name: Build and install Swig from source
        run: |
          yum install -y pcre-devel
          echo "SWIG_DIR=/usr/local/swig/" >> "${GITHUB_ENV}"
          curl -L https://sourceforge.net/projects/swig/files/swig/swig-4.0.2/swig-4.0.2.tar.gz/download > swig.tar.gz
          tar -zxvf swig.tar.gz
          cd swig-4.0.2/
          ./configure --disable-dependency-tracking --prefix=$SWIG_DIR
          make clean
          make -j 2
          make install

      - name: install CMake using pip
        run: |
          /opt/python/cp38-cp38/bin/pip install cmake
          ln -s /opt/python/cp38-cp38/bin/cmake /usr/bin/cmake
          ln -s /opt/python/cp38-cp38/bin/ctest /usr/bin/ctest

      - name: Create libsbml build directory
        run: |
          mkdir ${{runner.workspace}}/build-libsbml
          pwd
          echo ${{runner.workspace}}

      - name: Configure CMake for libsbml
        working-directory: ${{runner.workspace}}/build-libsbml
        run: |
          cmake $GITHUB_WORKSPACE \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
          -DWITH_CHECK=True \
          -DWITH_CPP_NAMESPACE=${{matrix.with_namespace}} \
          -DLIBSBML_USE_STRICT_INCLUDES=${{matrix.strict}} \
          -DWITH_EXAMPLES=${{matrix.with_examples}} \
          -DWITH_LIBXML=OFF \
          ${{matrix.xml_parser_option}}=True \
          ${{matrix.package_option}} \
          ${{matrix.language_bindings}} \
          -DPYTHON_EXECUTABLE=/opt/python/cp38-cp38/bin/python \
          -DPYTHON_INCLUDE_DIR=/opt/python/cp38-cp38/include/python3.8/ \
          -DWITH_STATIC_RUNTIME=ON \
          -DPYTHON_USE_DYNAMIC_LOOKUP=ON

      - name: Build and Install libsbml
        working-directory: ${{runner.workspace}}/build-libsbml
        run: cmake --build . --config $BUILD_TYPE