name: CMake (rapid build on push)

#on:
  #push:
    #tags:
      #- v*
on:
  push:
    branches:
      - 'develop'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name:
      Build on ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        cpp_standard: [20]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout libsbml
        uses: actions/checkout@v3
        with:
          repository: sbmlteam/libsbml

